import { formatPHP } from "@/lib/currency";
import { usePosStore } from "@/stores/posStore";
import { trpc } from "@/lib/trpc";
import { Archive, Boxes, PackagePlus, RefreshCw, SlidersHorizontal } from "lucide-react";
import { FormEvent, useState } from "react";

export default function Inventory() {
  const { activeLocationId, user } = usePosStore();
  const [search, setSearch] = useState(""); const [productName, setProductName] = useState(""); const [sku, setSku] = useState(""); const [price, setPrice] = useState(""); const [costPrice, setCostPrice] = useState("");
  const [adjustProductId, setAdjustProductId] = useState(""); const [adjustQuantity, setAdjustQuantity] = useState(""); const [adjustNote, setAdjustNote] = useState("");
  const canManage = user?.role === "manager" || user?.role === "admin";
  const inventory = trpc.inventory.list.useQuery({ locationId: activeLocationId ?? 0, search: search || undefined }, { enabled: Boolean(activeLocationId), retry: false });
  const categories = trpc.categories.list.useQuery(undefined, { retry: false });
  const createProduct = trpc.products.create.useMutation({ onSuccess: () => { setProductName(""); setSku(""); setPrice(""); setCostPrice(""); inventory.refetch(); } });
  const adjust = trpc.inventory.adjust.useMutation({ onSuccess: () => { setAdjustQuantity(""); setAdjustNote(""); inventory.refetch(); } });
  const submitProduct = (event: FormEvent) => { event.preventDefault(); createProduct.mutate({ sku, name: productName, price, costPrice: costPrice || "0.00", taxRate: "0.12", isTaxInclusive: false }); };
  const submitAdjust = (event: FormEvent) => { event.preventDefault(); if (activeLocationId && adjustProductId) adjust.mutate({ locationId: activeLocationId, productId: Number(adjustProductId), quantityDelta: adjustQuantity, reason: "adjustment", note: adjustNote || undefined }); };

  if (!canManage) return <div className="rounded-2xl border border-[#dce3db] bg-white p-8 text-center"><Archive className="mx-auto h-8 w-8 text-[#6f8577]" /><h1 className="mt-4 text-xl font-semibold text-[#17352e]">Inventory management is restricted</h1><p className="mt-2 text-sm text-[#74827b]">Managers and admins can maintain catalog and stock records.</p></div>;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#738278]">Stock control</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#17352e]">Inventory</h1></div><div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-2xl border border-[#dce3db] bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Boxes className="h-5 w-5 text-[#2e6853]" /><h2 className="font-semibold text-[#17352e]">Location stock</h2></div><input value={search} onChange={event => setSearch(event.target.value)} className="h-9 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Find a product" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[670px] text-left text-sm"><thead className="border-b border-[#e7ece7] text-xs uppercase tracking-wide text-[#7c8a81]"><tr><th className="pb-3 font-semibold">Product</th><th className="pb-3 font-semibold">SKU</th><th className="pb-3 font-semibold">Price</th><th className="pb-3 font-semibold">On hand</th><th className="pb-3 font-semibold">Threshold</th></tr></thead><tbody>{inventory.data?.map(item => <tr key={item.productId} className="border-b border-[#eef1ee] last:border-0"><td className="py-4 font-semibold text-[#294137]">{item.name}</td><td className="py-4 text-[#6f7d74]">{item.sku}</td><td className="py-4">{formatPHP(item.priceOverride ?? item.price)}</td><td className={`py-4 font-semibold ${Number(item.quantity) <= Number(item.lowStockThreshold) ? "text-amber-700" : "text-[#2d6a4f]"}`}>{item.quantity}</td><td className="py-4 text-[#6f7d74]">{item.lowStockThreshold}</td></tr>)}</tbody></table>{!inventory.data?.length && <p className="py-12 text-center text-sm text-[#738278]">No inventory records match this location and search.</p>}</div></section>
      <div className="space-y-5"><form onSubmit={submitProduct} className="rounded-2xl border border-[#dce3db] bg-white p-5"><div className="flex items-center gap-2"><PackagePlus className="h-5 w-5 text-[#2e6853]" /><h2 className="font-semibold text-[#17352e]">Add catalog product</h2></div><div className="mt-4 grid gap-3"><input required value={productName} onChange={event => setProductName(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Product name" /><input required value={sku} onChange={event => setSku(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Unique SKU" /><div className="grid grid-cols-2 gap-3"><input required value={price} onChange={event => setPrice(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Sell price" /><input value={costPrice} onChange={event => setCostPrice(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Cost price" /></div><button disabled={createProduct.isPending} className="h-10 rounded-lg bg-[#17352e] text-sm font-semibold text-white">{createProduct.isPending ? "Adding…" : "Add product"}</button>{createProduct.error && <p className="text-xs text-red-700">{createProduct.error.message}</p>}</div></form><form onSubmit={submitAdjust} className="rounded-2xl border border-[#dce3db] bg-white p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-[#2e6853]" /><h2 className="font-semibold text-[#17352e]">Stock adjustment</h2></div><div className="mt-4 grid gap-3"><select required value={adjustProductId} onChange={event => setAdjustProductId(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm"><option value="">Select product</option>{inventory.data?.map(item => <option key={item.productId} value={item.productId}>{item.name}</option>)}</select><input required value={adjustQuantity} onChange={event => setAdjustQuantity(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Quantity change (+ or -)" /><input value={adjustNote} onChange={event => setAdjustNote(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Reason / note" /><button disabled={adjust.isPending} className="flex h-10 items-center justify-center gap-2 rounded-lg border border-[#2f644e] text-sm font-semibold text-[#24513f]"><RefreshCw className="h-4 w-4" />{adjust.isPending ? "Saving…" : "Apply adjustment"}</button>{adjust.error && <p className="text-xs text-red-700">{adjust.error.message}</p>}</div></form></div></div></div>;
}
