import { formatPHP } from "@/lib/currency";
import { usePosStore } from "@/stores/posStore";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Boxes, BrainCircuit, CircleDollarSign, Clock3, Gauge, Lightbulb, Package, ShieldCheck, Sparkles, Target, TrendingUp, UsersRound } from "lucide-react";
import { Link } from "wouter";

const statusStyles: Record<string, { badge: string; icon: typeof TrendingUp }> = {
  positive: { badge: "bg-[#dff7f0] text-[#147d78]", icon: TrendingUp },
  watch: { badge: "bg-[#fff1d6] text-[#a26d16]", icon: Activity },
  risk: { badge: "bg-[#fde7e1] text-[#b85649]", icon: AlertTriangle },
};

export default function Overview() {
  const { activeLocationId, user, locations, parkedOrders = [] } = usePosStore();
  const canManage = user?.role === "manager" || user?.role === "admin";
  const enabled = Boolean(activeLocationId && canManage);
  const lowStock = trpc.inventory.lowStock.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const sessions = trpc.cashSessions.list.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId), retry: false });
  const report = trpc.reports.locationDashboard.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const cashReport = trpc.reports.cashSessions.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const loyaltyReport = trpc.reports.loyalty.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const forecast = trpc.reports.aiForecast.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const activeLocation = locations.find(location => location.id === activeLocationId);
  const topProducts = report.data?.topProducts ?? [];
  const indicators = forecast.data?.indicators ?? [];
  const metricCards = [
    { label: "Sales today", value: canManage ? (report.isLoading ? "…" : formatPHP(report.data?.revenue ?? 0)) : "Restricted", note: canManage ? `${report.data?.transactionCount ?? 0} completed transactions` : "Manager access required", icon: CircleDollarSign, tone: "bg-[#d8f5ed] text-[#147d78]" },
    { label: "Open cash sessions", value: canManage ? (cashReport.isLoading ? "…" : String(cashReport.data?.openCount ?? 0)) : (sessions.isLoading ? "…" : String(sessions.data?.length ?? 0)), note: canManage ? `${cashReport.data?.closedCount ?? 0} recently closed` : "Live sessions at this location", icon: Boxes, tone: "bg-[#e3f1f8] text-[#327195]" },
    { label: "Low-stock alerts", value: canManage ? (lowStock.isLoading ? "…" : String(lowStock.data?.length ?? 0)) : "Restricted", note: canManage ? "Items at or below threshold" : "Manager access required", icon: Package, tone: "bg-[#fff1d6] text-[#b5791e]" },
    { label: "Active members", value: canManage ? (loyaltyReport.isLoading ? "…" : String(loyaltyReport.data?.activeMembers ?? 0)) : "Restricted", note: canManage ? `${loyaltyReport.data?.pointsIssuedToday ?? 0} points issued today` : "Manager access required", icon: UsersRound, tone: "bg-[#eee6fb] text-[#8052a6]" },
  ];

  return <div className="space-y-7">
    <header className="flex flex-col justify-between gap-5 md:flex-row md:items-end">
      <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#6b8881]">PosQ intelligence dashboard</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#173f3d]">Dashboard</h1><p className="mt-2 text-sm text-[#6e8882]">{activeLocation ? `${activeLocation.code} · ${activeLocation.name}` : "Choose a branch to view live operations."} <span className="mx-1 text-[#abc4bd]">·</span> {new Date().toLocaleDateString("en-PH", { dateStyle: "medium" })}</p></div>
      <div className="flex gap-2"><Link href="/members" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[#cfe1db] bg-white px-4 text-sm font-semibold text-[#28625d] transition hover:border-[#71c9ba]">Find customer</Link><Link href="/register" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#147d78] px-4 text-sm font-semibold text-white shadow-[0_12px_24px_-14px_#147d78] transition hover:bg-[#0f6864]">Open register <ArrowUpRight className="h-4 w-4" /></Link></div>
    </header>

    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metricCards.map(metric => { const Icon = metric.icon; return <article key={metric.label} className="posq-card p-5"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${metric.tone}`}><Icon className="h-5 w-5" /></div><p className="mt-5 text-sm font-medium text-[#6e8882]">{metric.label}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-[#173f3d]">{metric.value}</p><p className="mt-1 text-xs text-[#8ca49e]">{metric.note}</p></article>; })}</section>

    <section className="overflow-hidden rounded-3xl bg-[#103d3b] text-white shadow-[0_20px_55px_-28px_rgba(16,61,59,.55)]"><div className="grid gap-6 p-6 lg:grid-cols-[1.2fr_.8fr] lg:p-8"><div><div className="flex items-center gap-2 text-[#bceee3]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/10"><BrainCircuit className="h-5 w-5" /></span><span className="text-xs font-bold uppercase tracking-[0.18em]">AI operations analyst</span><span className="rounded-full bg-[#d9f99d] px-2 py-1 text-[10px] font-bold text-[#17352e]">LIVE SIGNAL</span></div><h2 className="mt-5 max-w-2xl text-2xl font-semibold tracking-tight">{canManage ? (forecast.isLoading ? "Reading today’s operating signals…" : forecast.data?.headline ?? "Building your branch forecast") : "Manager intelligence is ready when you are"}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c4ddd6]">{canManage ? (forecast.isLoading ? "PosQ is combining sales velocity, stock pressure, cash readiness, and member activity." : forecast.data?.forecast ?? "Complete more sales to generate a reliable branch forecast.") : "AI-powered predictions and indicators are available to managers and admins."}</p><div className="mt-6 flex flex-wrap gap-3"><span className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs text-[#d9eee9]"><Sparkles className="h-4 w-4 text-[#d9f99d]" /> Confidence {canManage ? `${Math.round(forecast.data?.confidence ?? 0)}%` : "Restricted"}</span><span className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs text-[#d9eee9]"><Gauge className="h-4 w-4 text-[#bceee3]" /> {report.data?.transactionCount ?? 0} signals today</span></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#bceee3]">Decision cue</p><Lightbulb className="h-5 w-5 text-[#d9f99d]" /></div><p className="mt-4 text-lg font-semibold text-white">{canManage ? (forecast.data?.indicators?.[0]?.action ?? "Keep the register moving") : "Open the manager dashboard"}</p><p className="mt-2 text-sm leading-5 text-[#b4d2ca]">{canManage ? (forecast.data?.indicators?.[0]?.detail ?? "PosQ will surface the strongest signal as your data changes.") : "Your role can still use Register and member workflows."}</p><Link href={canManage ? "/reports" : "/register"} className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[#d9f99d]">Review recommendation <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></div></section>

    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <article className="posq-card p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#4e8981]">Predictive indicators</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">What needs attention next</h2><p className="mt-1 text-sm text-[#78948d]">AI-ranked signals from today’s branch activity.</p></div><Target className="h-5 w-5 text-[#147d78]" /></div><div className="mt-5 grid gap-3 md:grid-cols-3">{indicators.length ? indicators.map((indicator: any) => { const style = statusStyles[indicator.status] ?? statusStyles.watch; const Icon = style.icon; return <div key={indicator.label} className="rounded-2xl border border-[#e2eee9] bg-[#fbfdfc] p-4"><div className="flex items-center justify-between"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${style.badge}`}><Icon className="h-3 w-3" /> {indicator.status}</span><span className="text-sm font-bold text-[#173f3d]">{indicator.value}</span></div><p className="mt-4 text-sm font-semibold text-[#285b56]">{indicator.label}</p><p className="mt-1 text-xs leading-5 text-[#78948d]">{indicator.detail}</p><p className="mt-3 text-[11px] font-bold uppercase tracking-wide text-[#147d78]">Next: {indicator.action}</p></div>; }) : <div className="md:col-span-3 rounded-2xl border border-dashed border-[#cfe1db] p-5 text-sm text-[#78948d]">{canManage ? "Generating predictive indicators…" : "Manager access required for predictive indicators."}</div>}</div></article>
      <article className="posq-card p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b18437]">Risk radar</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">Branch health</h2></div><ShieldCheck className="h-5 w-5 text-[#b5791e]" /></div><div className="mt-5 space-y-3"><RadarRow label="Revenue momentum" value={report.data?.transactionCount ? "Active" : "Building"} icon={TrendingUp} /><RadarRow label="Inventory readiness" value={canManage ? `${lowStock.data?.length ?? 0} alerts` : "Restricted"} icon={Package} /><RadarRow label="Cash discipline" value={canManage ? `${cashReport.data?.openCount ?? 0} open` : "Restricted"} icon={CircleDollarSign} /><RadarRow label="Customer engagement" value={canManage ? `${loyaltyReport.data?.activeMembers ?? 0} active` : "Restricted"} icon={UsersRound} /></div></article>
    </section>

    <section className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><article className="posq-card overflow-hidden"><div className="flex items-start justify-between bg-[#e9f8f4] p-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#4e8981]">Sales intelligence</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">Top products today</h2><p className="mt-1 max-w-xl text-sm text-[#66837d]">Use the live ranking to protect availability and guide your next replenishment decision.</p></div><BarChart3 className="h-5 w-5 text-[#147d78]" /></div><div className="p-6">{topProducts.length ? <div className="grid gap-2 sm:grid-cols-2">{topProducts.map((item, index) => <div key={`${item.sku}-${index}`} className="flex items-center justify-between rounded-xl bg-[#f7fbfa] px-3 py-3 text-sm"><span className="min-w-0 truncate"><span className="mr-2 text-xs font-bold text-[#8aada5]">0{index + 1}</span>{item.name}</span><span className="ml-2 font-semibold text-[#28625d]">{formatPHP(item.revenue)}</span></div>)}</div> : <p className="rounded-xl bg-[#f7fbfa] p-4 text-sm text-[#78948d]">No completed sales yet today.</p>}<Link href="/reports" className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[#147d78]">Open detailed reports <ArrowUpRight className="h-3 w-3" /></Link></div></article><article className="posq-card p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b18437]">Needs attention</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">Branch alerts</h2></div><AlertTriangle className="h-5 w-5 text-[#c9902d]" /></div><div className="mt-5 space-y-3"><AlertRow href="/inventory" icon={Package} label="Low-stock watch" value={canManage ? `${lowStock.data?.length ?? 0} items` : "Manager view"} tone="amber" /><AlertRow href="/cash-controls" icon={CircleDollarSign} label="Cash controls" value={canManage ? `${cashReport.data?.openCount ?? 0} open drawer(s)` : "Manager view"} tone="teal" /><AlertRow href="/members" icon={UsersRound} label="Customer tracking" value={canManage ? `${loyaltyReport.data?.activeMembers ?? 0} active members` : "Open member lookup"} tone="violet" /><AlertRow href="/register" icon={Clock3} label="Parked orders" value={`${parkedOrders.length} waiting`} tone="blue" /></div></article></section>

    <section className="grid gap-4 md:grid-cols-3"><FeatureTile href="/members" icon={UsersRound} title="Customer tracking" text="Review spend, visits, loyalty balances, and member e-cards." accent="teal" /><FeatureTile href="/operations" icon={CircleDollarSign} title="Expenses & drawer" text="Use branch operations and cash controls for accountable cash handling." accent="gold" /><FeatureTile href="/users" icon={Clock3} title="Staff attendance" text="Keep staff access and branch assignment ready for attendance workflows." accent="violet" /></section>
  </div>;
}

function RadarRow({ label, value, icon: Icon }: { label: string; value: string; icon: typeof TrendingUp }) { return <div className="flex items-center gap-3 rounded-xl bg-[#f7fbfa] px-3 py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e1f7f1] text-[#147d78]"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1 text-sm font-semibold text-[#2a5b57]">{label}</span><span className="text-xs font-bold text-[#39766f]">{value}</span></div>; }
function AlertRow({ href, icon: Icon, label, value, tone }: { href: string; icon: typeof Package; label: string; value: string; tone: string }) { const tones: Record<string, string> = { amber: "bg-[#fff4dd] text-[#b5791e]", teal: "bg-[#e1f7f1] text-[#25877b]", violet: "bg-[#f0e8fb] text-[#8052a6]", blue: "bg-[#e5f2f9] text-[#327195]" }; return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-[#e5efeb] p-3 transition hover:bg-[#f7fbfa]"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#2a5b57]">{label}</span><span className="block text-xs text-[#819b94]">{value}</span></span><ArrowUpRight className="h-4 w-4 text-[#9bb8b1]" /></Link>; }
function FeatureTile({ href, icon: Icon, title, text, accent }: { href: string; icon: typeof Package; title: string; text: string; accent: string }) { const tones: Record<string, string> = { teal: "bg-[#dff7f0] text-[#147d78]", gold: "bg-[#fff1d6] text-[#b5791e]", violet: "bg-[#eee6fb] text-[#8052a6]" }; return <Link href={href} className="posq-card flex gap-4 p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${tones[accent]}`}><Icon className="h-5 w-5" /></span><span><span className="block font-semibold text-[#245b57]">{title}</span><span className="mt-1 block text-sm leading-5 text-[#78948d]">{text}</span></span></Link>; }
