import { formatPHP } from "@/lib/currency";
import { usePosStore } from "@/stores/posStore";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, Boxes, Store, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function Overview() {
  const { activeLocationId, user, locations } = usePosStore();
  const canManage = user?.role === "manager" || user?.role === "admin";
  const lowStock = trpc.inventory.lowStock.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId && canManage), retry: false });
  const sessions = trpc.cashSessions.list.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId), retry: false });
  const report = trpc.reports.locationDashboard.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId && canManage), retry: false });
  const activeLocation = locations.find(location => location.id === activeLocationId);

  const metrics = [
    { label: "Today’s revenue", value: canManage ? (report.isLoading ? "…" : formatPHP(report.data?.revenue ?? 0)) : "Restricted", note: canManage ? `${report.data?.transactionCount ?? 0} completed sale(s)` : "Manager access required", icon: Store, tone: "bg-[#d9f99d] text-[#17352e]" },
    { label: "Open cash sessions", value: sessions.isLoading ? "…" : String(sessions.data?.length ?? 0), note: "Live sessions at this location", icon: Boxes, tone: "bg-[#d5f5f0] text-[#155d53]" },
    { label: "Low-stock alerts", value: canManage ? (lowStock.isLoading ? "…" : String(lowStock.data?.length ?? 0)) : "Restricted", note: canManage ? "At or below threshold" : "Manager access required", icon: UsersRound, tone: "bg-[#e8defa] text-[#5f3d96]" },
  ];

  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#738278]">Operations overview</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#17352e]">Good day, {user?.name?.split(" ")[0] || "team"}.</h1><p className="mt-2 text-sm text-[#6c7c73]">{activeLocation ? `${activeLocation.code} · ${activeLocation.name}` : "Choose a branch to view live operations."}</p></div><Link href="/register" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#17352e] px-4 text-sm font-semibold text-white transition hover:bg-[#25463d]">Open register <ArrowUpRight className="h-4 w-4" /></Link></div>
    <div className="grid gap-4 md:grid-cols-3">{metrics.map(metric => { const Icon = metric.icon; return <div key={metric.label} className="rounded-2xl border border-[#dce3db] bg-white p-5 shadow-[0_12px_32px_-24px_rgba(16,35,31,0.25)]"><div className={`grid h-10 w-10 place-items-center rounded-xl ${metric.tone}`}><Icon className="h-5 w-5" /></div><p className="mt-5 text-sm font-medium text-[#6c7c73]">{metric.label}</p><p className="mt-1 text-2xl font-semibold text-[#17352e]">{metric.value}</p><p className="mt-1 text-xs text-[#8a978f]">{metric.note}</p></div>; })}</div>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_0.85fr]"><section className="rounded-2xl border border-[#dce3db] bg-white p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold text-[#17352e]">Branch readiness</h2><p className="mt-1 text-sm text-[#718078]">Start a session, review inventory, then open the register.</p></div><span className="rounded-full bg-[#edf5ed] px-3 py-1 text-xs font-semibold text-[#2a654e]">Live workspace</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/operations" className="rounded-xl border border-[#e0e6e0] p-4 transition hover:border-[#88a696] hover:bg-[#f7fbf7]"><span className="text-xs font-bold uppercase tracking-wide text-[#789083]">1</span><p className="mt-2 font-semibold text-[#243c31]">Open cash session</p><p className="mt-1 text-xs leading-5 text-[#75827a]">Assign a register and opening float.</p></Link><Link href="/inventory" className="rounded-xl border border-[#e0e0e0] p-4 transition hover:border-[#88a696] hover:bg-[#f7fbf7]"><span className="text-xs font-bold uppercase tracking-wide text-[#789083]">2</span><p className="mt-2 font-semibold text-[#243c31]">Review stock</p><p className="mt-1 text-xs leading-5 text-[#75827a]">Receive inventory or check thresholds.</p></Link><Link href="/register" className="rounded-xl border border-[#e0e6e0] p-4 transition hover:border-[#88a696] hover:bg-[#f7fbf7]"><span className="text-xs font-bold uppercase tracking-wide text-[#789083]">3</span><p className="mt-2 font-semibold text-[#243c31]">Process sales</p><p className="mt-1 text-xs leading-5 text-[#75827a]">Attach members and issue receipts.</p></Link></div>{canManage && <div className="mt-6 border-t border-[#e6ece6] pt-5"><h3 className="text-sm font-semibold text-[#294137]">Top products today</h3>{report.data?.topProducts?.length ? <div className="mt-3 space-y-2">{report.data.topProducts.map((item, index) => <div key={`${item.sku}-${index}`} className="flex items-center justify-between rounded-lg bg-[#f7fbf7] px-3 py-2 text-sm"><span>{index + 1}. {item.name}</span><span className="font-semibold">{formatPHP(item.revenue)} · {item.quantity}</span></div>)}</div> : <p className="mt-3 text-sm text-[#74827b]">No completed sales yet today.</p>}</div>}</section>
      <section className="rounded-2xl border border-[#dce3db] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-[#17352e]">Low-stock watch</h2><p className="mt-1 text-sm text-[#718078]">Items at or below their branch threshold.</p></div><AlertTriangle className="h-5 w-5 text-amber-500" /></div>{!canManage ? <p className="mt-8 text-sm text-[#718078]">Managers can review branch low-stock alerts here.</p> : lowStock.isLoading ? <p className="mt-8 text-sm text-[#718078]">Loading low-stock alerts…</p> : (lowStock.data?.length ? <div className="mt-5 space-y-3">{lowStock.data.slice(0, 4).map(item => <div key={item.productId} className="flex items-center justify-between rounded-xl bg-[#fffaf0] px-3 py-3"><div><p className="text-sm font-semibold text-[#36493e]">{item.name}</p><p className="mt-0.5 text-xs text-[#7f7767]">{item.sku}</p></div><div className="text-right"><p className="text-sm font-semibold text-amber-700">{item.quantity}</p><p className="text-[11px] text-[#8b806b]">threshold {item.lowStockThreshold}</p></div></div>)}</div> : <div className="mt-8 rounded-xl bg-[#f7fbf7] p-4 text-sm text-[#527060]">No active low-stock alerts for this location.</div>)}</section></div>
  </div>;
}
