import { formatPHP } from "@/lib/currency";
import { usePosStore } from "@/stores/posStore";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, BarChart3, Boxes, CircleDollarSign, Clock3, Package, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function Overview() {
  const { activeLocationId, user, locations, parkedOrders } = usePosStore();
  const canManage = user?.role === "manager" || user?.role === "admin";
  const enabled = Boolean(activeLocationId && canManage);
  const lowStock = trpc.inventory.lowStock.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const sessions = trpc.cashSessions.list.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId), retry: false });
  const report = trpc.reports.locationDashboard.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const cashReport = trpc.reports.cashSessions.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const loyaltyReport = trpc.reports.loyalty.useQuery({ locationId: activeLocationId ?? 0 }, { enabled, retry: false });
  const activeLocation = locations.find(location => location.id === activeLocationId);
  const metricCards = [
    { label: "Sales today", value: canManage ? (report.isLoading ? "…" : formatPHP(report.data?.revenue ?? 0)) : "Restricted", note: canManage ? `${report.data?.transactionCount ?? 0} completed transactions` : "Manager access required", icon: CircleDollarSign, tone: "bg-[#d8f5ed] text-[#147d78]" },
    { label: "Open cash sessions", value: canManage ? (cashReport.isLoading ? "…" : String(cashReport.data?.openCount ?? 0)) : (sessions.isLoading ? "…" : String(sessions.data?.length ?? 0)), note: canManage ? `${cashReport.data?.closedCount ?? 0} recently closed` : "Live sessions at this location", icon: Boxes, tone: "bg-[#e3f1f8] text-[#327195]" },
    { label: "Low-stock alerts", value: canManage ? (lowStock.isLoading ? "…" : String(lowStock.data?.length ?? 0)) : "Restricted", note: canManage ? "Items at or below threshold" : "Manager access required", icon: Package, tone: "bg-[#fff1d6] text-[#b5791e]" },
    { label: "Active members", value: canManage ? (loyaltyReport.isLoading ? "…" : String(loyaltyReport.data?.activeMembers ?? 0)) : "Restricted", note: canManage ? `${loyaltyReport.data?.pointsIssuedToday ?? 0} points issued today` : "Manager access required", icon: UsersRound, tone: "bg-[#eee6fb] text-[#8052a6]" },
  ];
  return <div className="space-y-7">
    <header className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#6b8881]">PosQ operations center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#173f3d]">Good day, {user?.name?.split(" ")[0] || "team"}.</h1><p className="mt-2 text-sm text-[#6e8882]">{activeLocation ? `${activeLocation.code} · ${activeLocation.name}` : "Choose a branch to view live operations."} <span className="mx-1 text-[#abc4bd]">·</span> {new Date().toLocaleDateString("en-PH", { dateStyle: "medium" })}</p></div><div className="flex gap-2"><Link href="/members" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[#cfe1db] bg-white px-4 text-sm font-semibold text-[#28625d] transition hover:border-[#71c9ba]">Find customer</Link><Link href="/register" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#147d78] px-4 text-sm font-semibold text-white shadow-[0_12px_24px_-14px_#147d78] transition hover:bg-[#0f6864]">Open register <ArrowUpRight className="h-4 w-4" /></Link></div></header>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metricCards.map(metric => { const Icon = metric.icon; return <article key={metric.label} className="posq-card p-5"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${metric.tone}`}><Icon className="h-5 w-5" /></div><p className="mt-5 text-sm font-medium text-[#6e8882]">{metric.label}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-[#173f3d]">{metric.value}</p><p className="mt-1 text-xs text-[#8ca49e]">{metric.note}</p></article>; })}</section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
      <article className="posq-card overflow-hidden"><div className="flex items-start justify-between bg-[#e9f8f4] p-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#4e8981]">Today at a glance</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">Keep the branch moving</h2><p className="mt-1 max-w-xl text-sm text-[#66837d]">Your daily rhythm: prepare cash, keep shelves healthy, and make every customer visit count.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-[#28736b]">Live workspace</span></div><div className="grid gap-3 p-6 sm:grid-cols-3"><QuickLink href="/operations" step="01" icon={CircleDollarSign} title="Prepare cash" text="Open a drawer and set opening float." /><QuickLink href="/inventory" step="02" icon={Package} title="Check stock" text="Review thresholds and replenishment." /><QuickLink href="/register" step="03" icon={BarChart3} title="Serve customers" text="Sell, earn points, and issue receipts." /></div>{canManage && <div className="border-t border-[#e2efeb] px-6 py-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-[#245b57]">Top products today</h3><p className="mt-1 text-xs text-[#79948e]">Ranked by completed sales</p></div><Link href="/reports" className="text-xs font-semibold text-[#147d78]">View reports <ArrowUpRight className="inline h-3 w-3" /></Link></div>{report.data?.topProducts?.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{report.data.topProducts.map((item, index) => <div key={`${item.sku}-${index}`} className="flex items-center justify-between rounded-xl bg-[#f7fbfa] px-3 py-3 text-sm"><span><span className="mr-2 text-xs font-bold text-[#8aada5]">0{index + 1}</span>{item.name}</span><span className="font-semibold text-[#28625d]">{formatPHP(item.revenue)}</span></div>)}</div> : <p className="mt-4 rounded-xl bg-[#f7fbfa] p-4 text-sm text-[#78948d]">No completed sales yet today.</p>}</div>}</article>
      <article className="posq-card p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b18437]">Needs attention</p><h2 className="mt-1 text-xl font-semibold text-[#173f3d]">Branch alerts</h2></div><AlertTriangle className="h-5 w-5 text-[#c9902d]" /></div><div className="mt-5 space-y-3"><AlertRow href="/inventory" icon={Package} label="Low-stock watch" value={canManage ? `${lowStock.data?.length ?? 0} items` : "Manager view"} tone="amber" /><AlertRow href="/cash-controls" icon={CircleDollarSign} label="Cash controls" value={canManage ? `${cashReport.data?.openCount ?? 0} open drawer(s)` : "Manager view"} tone="teal" /><AlertRow href="/members" icon={UsersRound} label="Customer tracking" value={canManage ? `${loyaltyReport.data?.activeMembers ?? 0} active members` : "Open member lookup"} tone="violet" /><AlertRow href="/register" icon={Clock3} label="Parked orders" value={`${parkedOrders.length} waiting` } tone="blue" /></div><div className="mt-5 rounded-2xl bg-[#f7fbfa] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#78948d]">Cash variance monitor</p><p className="mt-2 text-2xl font-semibold text-[#173f3d]">{canManage ? formatPHP(cashReport.data?.totalVariance ?? 0) : "Restricted"}</p><p className="mt-1 text-xs text-[#78948d]">Across recent closed sessions</p></div></article>
    </section>
    <section className="grid gap-4 md:grid-cols-3"><FeatureTile href="/members" icon={UsersRound} title="Customer tracking" text="Review spend, visits, loyalty balances, and member e-cards." accent="teal" /><FeatureTile href="/operations" icon={CircleDollarSign} title="Expenses & drawer" text="Use branch operations and cash controls for accountable cash handling." accent="gold" /><FeatureTile href="/users" icon={Clock3} title="Staff attendance" text="Keep staff access and branch assignment ready for attendance workflows." accent="violet" /></section>
  </div>;
}
function QuickLink({ href, step, icon: Icon, title, text }: { href: string; step: string; icon: typeof Package; title: string; text: string }) { return <Link href={href} className="group rounded-2xl border border-[#dbeae5] bg-white p-4 transition hover:-translate-y-0.5 hover:border-[#70c7b8] hover:shadow-md"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#78a39a]">{step}</span><Icon className="h-4 w-4 text-[#58ad9f]" /></div><p className="mt-4 font-semibold text-[#245b57]">{title}</p><p className="mt-1 text-xs leading-5 text-[#78948d]">{text}</p></Link>; }
function AlertRow({ href, icon: Icon, label, value, tone }: { href: string; icon: typeof Package; label: string; value: string; tone: string }) { const tones: Record<string, string> = { amber: "bg-[#fff4dd] text-[#b5791e]", teal: "bg-[#e1f7f1] text-[#25877b]", violet: "bg-[#f0e8fb] text-[#8052a6]", blue: "bg-[#e5f2f9] text-[#327195]" }; return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-[#e5efeb] p-3 transition hover:bg-[#f7fbfa]"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#2a5b57]">{label}</span><span className="block text-xs text-[#819b94]">{value}</span></span><ArrowUpRight className="h-4 w-4 text-[#9bb8b1]" /></Link>; }
function FeatureTile({ href, icon: Icon, title, text, accent }: { href: string; icon: typeof Package; title: string; text: string; accent: string }) { const tones: Record<string, string> = { teal: "bg-[#dff7f0] text-[#147d78]", gold: "bg-[#fff1d6] text-[#b5791e]", violet: "bg-[#eee6fb] text-[#8052a6]" }; return <Link href={href} className="posq-card flex gap-4 p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${tones[accent]}`}><Icon className="h-5 w-5" /></span><span><span className="block font-semibold text-[#245b57]">{title}</span><span className="mt-1 block text-sm leading-5 text-[#78948d]">{text}</span></span></Link>; }
