import { trpc } from "@/lib/trpc";
import { usePosStore } from "@/stores/posStore";
import { CalendarClock, CalendarDays, CheckSquare, ChevronRight, ClipboardList, Clock3, FileClock, UserCheck } from "lucide-react";
import { useState } from "react";

type Section = "clock" | "dtr" | "process" | "scheduler" | "requests";
const sections: { id: Section; label: string; icon: typeof Clock3; description: string }[] = [
  { id: "clock", label: "Clock In / Clock Out", icon: Clock3, description: "Record attendance against the active branch with a clear audit trail." },
  { id: "dtr", label: "Daily Time Record", icon: ClipboardList, description: "Review attendance events by location and employee." },
  { id: "process", label: "DTR Process", icon: CheckSquare, description: "Identify complete records ready for payroll and incomplete punches." },
  { id: "scheduler", label: "Calendar Scheduler", icon: CalendarDays, description: "Create recurring Philippine retail shifts with grace periods." },
  { id: "requests", label: "Schedule Request logs", icon: FileClock, description: "Submit, review, and process time corrections, overtime, and schedule changes." },
];

export default function Timekeeping() {
  const { user } = usePosStore(); const [section, setSection] = useState<Section>(() => { const value = new URLSearchParams(window.location.search).get("section") as Section | null; return value && sections.some(item => item.id === value) ? value : "clock"; }); const current = sections.find(item => item.id === section)!; const Icon = current.icon;
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#738278]">Workforce operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#17352e]">Timekeeping</h1><p className="mt-2 max-w-3xl text-sm text-[#74827b]">Attendance, daily time records, schedules, and request approvals for Philippine retail teams.</p></header><div className="grid gap-5 xl:grid-cols-[270px_1fr]"><aside className="posq-card h-fit p-3"><div className="mb-3 flex items-center gap-2 px-3 py-2"><CalendarClock className="h-5 w-5 text-[#147d78]" /><span className="font-semibold text-[#17352e]">Timekeeping</span></div><nav className="space-y-1">{sections.map(item => { const ItemIcon = item.icon; return <button key={item.id} type="button" onClick={() => setSection(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${section === item.id ? "bg-[#e1f7f1] font-semibold text-[#147d78]" : "text-[#61746c] hover:bg-[#f3f8f5]"}`}><ItemIcon className="h-4 w-4 shrink-0" /><span className="min-w-0 flex-1">{item.label}</span><ChevronRight className="h-4 w-4 text-[#b1c2bb]" /></button>; })}</nav></aside><main><div className="posq-card mb-5 flex items-start gap-3 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#dff7f0] text-[#147d78]"><Icon className="h-5 w-5" /></span><div><h2 className="text-xl font-semibold text-[#17352e]">{current.label}</h2><p className="mt-1 text-sm text-[#74827b]">{current.description}</p></div></div>{section === "clock" && <Clock />}{section === "dtr" && <DTR />}{section === "process" && <Process />}{section === "scheduler" && <Scheduler />}{section === "requests" && <Requests userRole={user?.role ?? "cashier"} />}</main></div></div>;
}

function Clock() { const { activeLocationId } = usePosStore(); const attendance = trpc.timekeeping.clock.status.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId) }); const record = trpc.timekeeping.clock.record.useMutation({ onSuccess: () => attendance.refetch() }); const latest = attendance.data?.[0]; const canTimeOut = latest?.eventType === "time_in"; return <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="posq-card p-6 text-center"><UserCheck className="mx-auto h-10 w-10 text-[#147d78]" /><p className="mt-4 text-sm text-[#74827b]">{new Date().toLocaleString("en-PH", { dateStyle: "full", timeStyle: "short" })}</p><p className="mt-3 text-2xl font-semibold text-[#17352e]">{canTimeOut ? "You are clocked in" : "Ready to start your shift"}</p><div className="mt-5 flex justify-center gap-3"><button disabled={!activeLocationId || record.isPending || canTimeOut} onClick={() => record.mutate({ locationId: activeLocationId!, eventType: "time_in" })} className="h-11 rounded-xl bg-[#17352e] px-5 text-sm font-semibold text-white disabled:opacity-40">{record.isPending ? "Saving…" : "Clock In"}</button><button disabled={!activeLocationId || record.isPending || !canTimeOut} onClick={() => record.mutate({ locationId: activeLocationId!, eventType: "time_out" })} className="h-11 rounded-xl border border-[#cbdad2] px-5 text-sm font-semibold text-[#39766f] disabled:opacity-40">Clock Out</button></div>{!activeLocationId && <p className="mt-3 text-xs text-amber-700">Select an active location before clocking in.</p>}</section><section className="posq-card p-5"><h3 className="font-semibold text-[#17352e]">My recent punches</h3><div className="mt-4 space-y-2">{attendance.data?.map(row => <div key={row.id} className="flex items-center justify-between rounded-xl bg-[#f6faf8] p-3 text-sm"><span className="font-semibold text-[#2a5b57]">{row.eventType === "time_in" ? "Time in" : "Time out"}</span><span className="text-xs text-[#789087]">{new Date(row.createdAt).toLocaleString("en-PH")}</span></div>)}{!attendance.data?.length && <p className="py-8 text-center text-sm text-[#789087]">No punches recorded for this location.</p>}</div></section></div>; }

function DTR() { const { activeLocationId } = usePosStore(); const dtr = trpc.timekeeping.dtr.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId) }); return <section className="posq-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-[#17352e]">Daily Time Record</h3><p className="mt-1 text-xs text-[#74827b]">Latest attendance events for the selected branch.</p></div><CalendarClock className="h-5 w-5 text-[#147d78]" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-[#e5eee9] text-xs uppercase tracking-wide text-[#74827b]"><tr><th className="pb-3">Employee</th><th className="pb-3">Event</th><th className="pb-3">Recorded at</th><th className="pb-3">Note</th></tr></thead><tbody>{dtr.data?.map(row => <tr key={row.id} className="border-b border-[#eef3ef]"><td className="py-3 font-semibold text-[#2a5b57]">{row.staffName || `Staff #${row.userId}`}</td><td className="py-3">{row.eventType === "time_in" ? "Clock In" : "Clock Out"}</td><td className="py-3 text-xs text-[#60766e]">{new Date(row.createdAt).toLocaleString("en-PH")}</td><td className="py-3 text-xs text-[#789087]">{row.note || "—"}</td></tr>)}</tbody></table>{!dtr.data?.length && <p className="py-8 text-center text-sm text-[#789087]">No daily time records.</p>}</div></section>; }

function Process() { const { activeLocationId } = usePosStore(); const process = trpc.timekeeping.process.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId) }); return <section className="posq-card p-5"><h3 className="font-semibold text-[#17352e]">DTR processing queue</h3><p className="mt-1 text-xs text-[#74827b]">Review punch pairs before sending time records to payroll.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{process.data?.map(row => <div key={row.userId} className="rounded-xl bg-[#f6faf8] p-4"><p className="font-semibold text-[#2a5b57]">{row.staffName || `Staff #${row.userId}`}</p><p className="mt-2 text-xs text-[#789087]">In: {row.timeIn ? new Date(row.timeIn).toLocaleString("en-PH") : "Missing"}</p><p className="text-xs text-[#789087]">Out: {row.timeOut ? new Date(row.timeOut).toLocaleString("en-PH") : "Missing"}</p><span className={`mt-3 inline-block rounded-full px-2 py-1 text-[10px] font-bold uppercase ${row.status === "Ready for payroll" ? "bg-[#dff7f0] text-[#147d78]" : "bg-amber-100 text-amber-800"}`}>{row.status}</span></div>)}</div>{!process.data?.length && <p className="py-8 text-center text-sm text-[#789087]">No records to process.</p>}</section>; }

function Scheduler() { const schedules = trpc.timekeeping.schedules.list.useQuery(); const create = trpc.timekeeping.schedules.create.useMutation({ onSuccess: () => schedules.refetch() }); const [form, setForm] = useState({ name: "", startTime: "09:00", endTime: "18:00", graceMinutes: 15, daysOfWeek: [1, 2, 3, 4, 5] }); return <section className="posq-card p-5"><h3 className="font-semibold text-[#17352e]">Calendar scheduler</h3><p className="mt-1 text-xs text-[#74827b]">Create reusable weekly shifts with grace-period rules.</p><div className="mt-4 grid gap-3 md:grid-cols-5"><input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="input md:col-span-2" placeholder="Schedule name" /><input type="time" value={form.startTime} onChange={event => setForm({ ...form, startTime: event.target.value })} className="input" /><input type="time" value={form.endTime} onChange={event => setForm({ ...form, endTime: event.target.value })} className="input" /><input type="number" value={form.graceMinutes} onChange={event => setForm({ ...form, graceMinutes: Number(event.target.value) })} className="input" min={0} placeholder="Grace minutes" /></div><button disabled={!form.name || create.isPending} onClick={() => create.mutate(form)} className="mt-4 h-10 rounded-xl bg-[#17352e] px-4 text-sm font-semibold text-white disabled:opacity-50">Add schedule</button><div className="mt-5 grid gap-3 sm:grid-cols-2">{schedules.data?.map(schedule => <div key={schedule.id} className="rounded-xl bg-[#f6faf8] p-4"><p className="font-semibold text-[#2a5b57]">{schedule.name}</p><p className="mt-1 text-sm text-[#60766e]">{schedule.startTime} – {schedule.endTime}</p><p className="mt-1 text-xs text-[#789087]">Grace period: {schedule.graceMinutes} minutes</p></div>)}</div></section>; }

function Requests({ userRole }: { userRole: string }) { const mine = trpc.timekeeping.requests.mine.useQuery(); const all = trpc.timekeeping.requests.all.useQuery(undefined, { enabled: userRole === "manager" || userRole === "admin" }); const create = trpc.timekeeping.requests.create.useMutation({ onSuccess: () => { mine.refetch(); all.refetch(); } }); const update = trpc.timekeeping.requests.update.useMutation({ onSuccess: () => all.refetch() }); const [form, setForm] = useState({ requestedDate: "", requestType: "time_correction" as const, reason: "" }); const rows = userRole === "manager" || userRole === "admin" ? all.data : mine.data; return <section className="posq-card p-5"><h3 className="font-semibold text-[#17352e]">Schedule request logs</h3><p className="mt-1 text-xs text-[#74827b]">Submit corrections or overtime requests; managers can approve or reject them.</p><div className="mt-4 grid gap-3 md:grid-cols-[180px_200px_1fr_auto]"><input type="date" value={form.requestedDate} onChange={event => setForm({ ...form, requestedDate: event.target.value })} className="input" /><select value={form.requestType} onChange={event => setForm({ ...form, requestType: event.target.value as typeof form.requestType })} className="input"><option value="time_correction">Time correction</option><option value="schedule_change">Schedule change</option><option value="overtime">Overtime</option></select><input value={form.reason} onChange={event => setForm({ ...form, reason: event.target.value })} className="input" placeholder="Reason" /><button disabled={!form.requestedDate || form.reason.length < 3 || create.isPending} onClick={() => create.mutate({ ...form, requestedDate: new Date(form.requestedDate) })} className="h-10 rounded-xl bg-[#17352e] px-4 text-sm font-semibold text-white disabled:opacity-50">Submit</button></div><div className="mt-5 space-y-2">{rows?.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#f6faf8] p-4 text-sm"><div><p className="font-semibold text-[#2a5b57]">{row.requestType.replace("_", " ")}</p><p className="text-xs text-[#789087]">{new Date(row.requestedDate).toLocaleDateString("en-PH")} · {row.reason}</p></div><div className="flex items-center gap-3"><span className="text-xs font-bold uppercase text-[#147d78]">{row.status}</span>{(userRole === "manager" || userRole === "admin") && row.status === "pending" && <><button onClick={() => update.mutate({ id: row.id, status: "approved" })} className="text-xs font-semibold text-[#147d78]">Approve</button><button onClick={() => update.mutate({ id: row.id, status: "rejected" })} className="text-xs font-semibold text-red-700">Reject</button></>}</div></div>)}{!rows?.length && <p className="py-8 text-center text-sm text-[#789087]">No schedule requests.</p>}</div></section>; }
