import { usePosStore } from "@/stores/posStore";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ArrowRightLeft, Truck } from "lucide-react";
import { FormEvent, useState } from "react";

export default function Transfers() {
  const { activeLocationId, locations } = usePosStore();
  const [destinationLocationId, setDestinationLocationId] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState("1");
  const inventory = trpc.inventory.list.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId), retry: false });
  const transfers = trpc.stockTransfers.list.useQuery({ locationId: activeLocationId ?? 0 }, { enabled: Boolean(activeLocationId), retry: false });
  const request = trpc.stockTransfers.request.useMutation({ onSuccess: () => { setProductId(""); setQuantity("1"); transfers.refetch(); } });
  const submit = (event: FormEvent) => { event.preventDefault(); if (activeLocationId && destinationLocationId && productId) request.mutate({ sourceLocationId: activeLocationId, destinationLocationId: Number(destinationLocationId), items: [{ productId: Number(productId), quantityRequested: quantity }] }); };
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#738278]">Multi-location inventory</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#17352e]">Stock transfers</h1></div><div className="grid gap-5 lg:grid-cols-[0.75fr_1.25fr]"><form onSubmit={submit} className="rounded-2xl border border-[#dce3db] bg-white p-6"><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-[#2e6853]" /><h2 className="font-semibold text-[#17352e]">Request transfer</h2></div><p className="mt-2 text-sm text-[#718078]">Ship stock from this active location to another assigned branch.</p><div className="mt-5 grid gap-3"><select required value={destinationLocationId} onChange={event => setDestinationLocationId(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm"><option value="">Destination location</option>{locations.filter(location => location.id !== activeLocationId).map(location => <option key={location.id} value={location.id}>{location.code} · {location.name}</option>)}</select><select required value={productId} onChange={event => setProductId(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm"><option value="">Product to transfer</option>{inventory.data?.map(item => <option key={item.productId} value={item.productId}>{item.name} ({item.quantity})</option>)}</select><input required value={quantity} onChange={event => setQuantity(event.target.value)} className="h-10 rounded-lg border border-[#d6ded7] px-3 text-sm" placeholder="Quantity" /><button disabled={request.isPending} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-[#17352e] text-sm font-semibold text-white">{request.isPending ? "Creating…" : "Create transfer"}<ArrowRight className="h-4 w-4" /></button>{request.error && <p className="text-xs text-red-700">{request.error.message}</p>}</div></form><section className="rounded-2xl border border-[#dce3db] bg-white p-6"><div className="flex items-center gap-2"><ArrowRightLeft className="h-5 w-5 text-[#2e6853]" /><h2 className="font-semibold text-[#17352e]">Transfer queue</h2></div><div className="mt-4 space-y-3">{transfers.data?.length ? transfers.data.map(transfer => <div key={transfer.id} className="flex items-center justify-between rounded-xl border border-[#e2e8e2] px-4 py-3"><div><p className="text-sm font-semibold text-[#294137]">{transfer.transferNumber}</p><p className="mt-1 text-xs text-[#74827b]">Source #{transfer.sourceLocationId} <span className="mx-1">→</span> Destination #{transfer.destinationLocationId}</p></div><span className="rounded-full bg-[#edf5ed] px-3 py-1 text-xs font-semibold capitalize text-[#2d6a4f]">{transfer.status}</span></div>) : <p className="py-12 text-center text-sm text-[#74827b]">No transfers have been requested for this location.</p>}</div></section></div></div>;
}
